// GENERATED by ng2recomp/tools/native_gpu/gen_trace_hooks.py. The native-GPU
// call-census tracer: every Direct3D library entry point and device state
// setter has a mid-asm hook at its first instruction that counts the call and
// keeps the first argument samples; a census goes to the log every 10 s
// ([ngpu] lines). Enabled by the ngpu_trace cvar (default off: the hooks
// cost one load and one compare each when off).
#include <rex/cvar.h>
#include <rex/logging.h>
#include <rex/ppc/context.h>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <mutex>

REXCVAR_DEFINE_BOOL(ngpu_trace, false, "GPU", "Log a call census of the Direct3D library entry points every 10 s");
REXCVAR_DEFINE_INT32(ngpu_trace_frame, 600, "GPU", "Frame after which the one verbatim frame transcript is dumped - set past the menus so it captures a real 3D frame, not the title");

namespace {
constexpr int kHooks = 108;
constexpr int kSamples = 4;
struct Entry { uint32_t addr; const char* label; };
const Entry kEntries[kHooks] = {
  {0x83734370, "lib sites=3 SET_BIN_MASK_HI,SET_BIN_MASK_LO,SET_BIN_SELECT_LO"},
  {0x83734810, "lib sites=1"},
  {0x83734A78, "lib sites=1"},
  {0x83734B10, "lib sites=1"},
  {0x837351D0, "lib sites=1"},
  {0x83735CF8, "lib sites=1"},
  {0x83736290, "lib sites=1"},
  {0x837363D8, "lib sites=55"},
  {0x83736568, "lib sites=55"},
  {0x83736908, "lib sites=1"},
  {0x837369A8, "lib sites=4"},
  {0x83736A28, "lib sites=1"},
  {0x83736DC8, "lib sites=6"},
  {0x83736EC8, "lib sites=12"},
  {0x83736F48, "lib sites=8"},
  {0x83737068, "lib sites=2"},
  {0x837370F0, "lib sites=10"},
  {0x83737180, "lib sites=29"},
  {0x837374E8, "lib sites=30"},
  {0x837377C0, "lib sites=1"},
  {0x83737950, "lib sites=2"},
  {0x83737BB8, "lib sites=1"},
  {0x83737C98, "lib sites=2"},
  {0x83737CB0, "lib sites=7"},
  {0x83737D08, "lib sites=2"},
  {0x83737D48, "lib sites=2"},
  {0x83737D58, "lib sites=1"},
  {0x83737DF0, "lib sites=1"},
  {0x83738A38, "lib sites=0 SET_BIN_MASK_LO"},
  {0x837390C8, "lib sites=21"},
  {0x83739188, "lib sites=1"},
  {0x83739318, "lib sites=1"},
  {0x83739360, "lib sites=4"},
  {0x837397E0, "lib sites=2"},
  {0x83739CF0, "lib sites=0 INDIRECT_BUFFER"},
  {0x8373A088, "lib sites=0 EVENT_WRITE_SHD"},
  {0x8373A3D0, "lib sites=6"},
  {0x8373A4D0, "lib sites=1"},
  {0x8373A5A8, "lib sites=1"},
  {0x8373A7D0, "lib sites=2"},
  {0x8373A8C0, "lib sites=3"},
  {0x8373A918, "lib sites=2 ME_INIT VdSetSystemCommandBufferGpuIdentifierAddress,VdInitializeRingBuffer,VdEnableRingBufferRPtrWriteBack,VdSetSystemCommandBufferGpuIdentifierAddress"},
  {0x8373B060, "lib sites=0 DRAW_INDX_2"},
  {0x8373B1F8, "lib sites=26"},
  {0x8373B2E0, "lib sites=10"},
  {0x8373B3C8, "lib sites=20"},
  {0x8373B4D8, "lib sites=34"},
  {0x8373B790, "lib sites=18"},
  {0x8373B880, "lib sites=32"},
  {0x8373BAD8, "lib sites=3"},
  {0x8373BBE0, "lib sites=12"},
  {0x8373BC68, "lib sites=14"},
  {0x8373BD50, "lib sites=49"},
  {0x8373C1F0, "lib sites=4"},
  {0x8373C720, "lib sites=3"},
  {0x8373CB08, "lib sites=6"},
  {0x8373D570, "lib sites=43 IM_LOAD_IMMEDIATE,INVALIDATE_STATE,WAIT_REG_MEM"},
  {0x8373E5B8, "lib sites=3 WAIT_REG_MEM"},
  {0x8373E848, "lib sites=13"},
  {0x8373E970, "lib sites=20"},
  {0x8373E9E8, "lib sites=40"},
  {0x8373EA68, "lib sites=1"},
  {0x8373EA90, "lib sites=8"},
  {0x8373EB20, "lib sites=2"},
  {0x8373EBE8, "lib sites=1"},
  {0x8373EC38, "lib sites=1"},
  {0x8373EC48, "lib sites=1"},
  {0x8373ECF8, "lib sites=1"},
  {0x8373ED40, "lib sites=1"},
  {0x8373ED50, "lib sites=1"},
  {0x8373EE40, "lib sites=1"},
  {0x8373EF78, "lib sites=1"},
  {0x8373F180, "lib sites=1"},
  {0x8373F498, "lib sites=0 VdGetCurrentDisplayGamma"},
  {0x8373F928, "lib sites=0 COND_WRITE"},
  {0x8373FA08, "lib sites=0 COND_WRITE"},
  {0x8373FAF8, "lib sites=1"},
  {0x8373FB10, "lib sites=1"},
  {0x83740290, "lib sites=0 REG_TO_MEM"},
  {0x83741B08, "lib sites=2 VdQueryVideoMode"},
  {0x83741DC0, "lib sites=2"},
  {0x83741ED8, "lib sites=0 VdShutdownEngines"},
  {0x83741F00, "lib sites=0 VdInitializeEngines,VdSetGraphicsInterruptCallback,VdIsHSIOTrainingSucceeded"},
  {0x83742128, "lib sites=0 VdSetSystemCommandBufferGpuIdentifierAddress,VdSetGraphicsInterruptCallback,VdShutdownEngines"},
  {0x83742C10, "lib sites=0 EVENT_WRITE"},
  {0x83743268, "lib sites=0 WAIT_REG_MEM"},
  {0x83743F80, "lib sites=0 IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x83744D90, "lib sites=1"},
  {0x837452C0, "lib sites=1 VdGetSystemCommandBuffer,VdSwap,VdSetDisplayMode,VdGetCurrentDisplayInformation,VdPersistDisplay"},
  {0x837459D8, "lib sites=2"},
  {0x83745B20, "lib sites=2"},
  {0x83746F50, "lib sites=0 VdQueryVideoMode"},
  {0x83747498, "lib sites=0 VdQueryVideoFlags"},
  {0x837475C0, "lib sites=0 VdInitializeScalerCommandBuffer"},
  {0x83747790, "lib sites=0 VdCallGraphicsNotificationRoutines"},
  {0x83747940, "lib sites=0 EVENT_WRITE_SHD"},
  {0x83747BB0, "lib sites=0 SET_BIN_SELECT_LO"},
  {0x83748A18, "lib sites=1"},
  {0x83748C08, "lib sites=2"},
  {0x83748F18, "lib sites=0 REG_RMW"},
  {0x83749AE0, "lib sites=0 EVENT_WRITE_SHD"},
  {0x83749BC0, "lib sites=0 VdEnableDisableClockGating,VdEnableDisableClockGating"},
  {0x8374B300, "lib sites=0 VdGetCurrentDisplayInformation"},
  {0x8374B6A8, "lib sites=0 VdGetCurrentDisplayInformation"},
  {0x8374BAC8, "lib sites=0 EVENT_WRITE,IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x8374C4D0, "lib sites=0 VdRetrainEDRAMWorker,VdRetrainEDRAM,VdRetrainEDRAM"},
  {0x8374C5B8, "lib sites=4 SET_BIN_MASK_LO"},
  {0x8374C728, "lib sites=1 EVENT_WRITE"},
};
std::atomic<uint64_t> g_count[kHooks];
uint64_t g_last[kHooks];
std::atomic<int> g_nsamples[kHooks];
uint32_t g_samples[kHooks][kSamples][8];
std::atomic<uint32_t> g_tick{0};
constexpr uint32_t kFrameMarkerAddr = 0x837452C0;
constexpr int kSeqMax = 8192;
uint16_t g_seq[kSeqMax];
int g_seq_n = 0;
bool g_seq_done = false;
uint64_t g_frame_no = 0;
uint64_t g_frame_base[kHooks];
std::mutex g_dump_mutex;
auto g_t0 = std::chrono::steady_clock::now();
double g_next_dump = 10.0;

void Dump() {
  std::lock_guard<std::mutex> lock(g_dump_mutex);
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_t0).count();
  if (t < g_next_dump) return;
  g_next_dump = t + 10.0;
  REXLOG_INFO("[ngpu] census at {:.1f} s (calls total / last 10 s)", t);
  for (int i = 0; i < kHooks; ++i) {
    const uint64_t c = g_count[i].load(std::memory_order_relaxed);
    if (c == 0) continue;
    const uint64_t d = c - g_last[i];
    g_last[i] = c;
    std::string s;
    const int ns = g_nsamples[i].load(std::memory_order_acquire);
    if (ns > 0 && ns <= kSamples) {
      for (int k = 0; k < ns; ++k) {
        const uint32_t* a = g_samples[i][k];
        s += fmt::format(" [{:08X} {:08X} {:08X} {:08X} {:08X} {:08X} {:08X} {:08X}]",
                         a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]);
      }
      g_nsamples[i].store(kSamples + 1, std::memory_order_release);  // printed once
    }
    REXLOG_INFO("[ngpu] sub_{:08X} {} calls={} +{}{}", kEntries[i].addr, kEntries[i].label, c, d, s);
  }
}

void FrameEnd() {
  std::lock_guard<std::mutex> lock(g_dump_mutex);
  ++g_frame_no;
  // One transcript, once, after warmup - the title screen is not the frame
  // worth recording and the first frames are atypical.
  if (!g_seq_done && g_frame_no > REXCVAR_GET(ngpu_trace_frame) && g_seq_n > 0) {
    g_seq_done = true;
    REXLOG_INFO("[ngpu] FRAME TRANSCRIPT, frame {}, {} calls in order", g_frame_no, g_seq_n);
    // Run-length encoded: order is preserved exactly, repeats collapse so
    // the log stays readable. "Ax12" means twelve consecutive calls to A.
    std::string line;
    int run = 1;
    for (int k = 1; k <= g_seq_n; ++k) {
      if (k < g_seq_n && g_seq[k] == g_seq[k - 1]) { ++run; continue; }
      const uint32_t a = kEntries[g_seq[k - 1]].addr;
      line += run > 1 ? fmt::format(" {:08X}x{}", a, run) : fmt::format(" {:08X}", a);
      run = 1;
      if (line.size() > 900) { REXLOG_INFO("[ngpu] seq{}", line); line.clear(); }
    }
    if (!line.empty()) REXLOG_INFO("[ngpu] seq{}", line);
    REXLOG_INFO("[ngpu] PER-FRAME counts for that frame:");
    for (int i = 0; i < kHooks; ++i) {
      const uint64_t c = g_count[i].load(std::memory_order_relaxed);
      const uint64_t d = c - g_frame_base[i];
      if (d) REXLOG_INFO("[ngpu] frame sub_{:08X} {} x{}", kEntries[i].addr, kEntries[i].label, d);
    }
  }
  for (int i = 0; i < kHooks; ++i) g_frame_base[i] = g_count[i].load(std::memory_order_relaxed);
  g_seq_n = 0;
}

inline void Trace(int i, PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6,
                  PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) {
  if (!REXCVAR_GET(ngpu_trace)) return;
  g_count[i].fetch_add(1, std::memory_order_relaxed);
  int ns = g_nsamples[i].load(std::memory_order_relaxed);
  if (ns < kSamples) {
    uint32_t* a = g_samples[i][ns];
    a[0] = r3.u32; a[1] = r4.u32; a[2] = r5.u32; a[3] = r6.u32;
    a[4] = r7.u32; a[5] = r8.u32; a[6] = r9.u32; a[7] = r10.u32;
    g_nsamples[i].store(ns + 1, std::memory_order_release);
  }
  if (!g_seq_done) {
    std::lock_guard<std::mutex> lock(g_dump_mutex);
    if (g_seq_n < kSeqMax) g_seq[g_seq_n++] = static_cast<uint16_t>(i);
  }
  if (kFrameMarkerAddr && kEntries[i].addr == kFrameMarkerAddr) FrameEnd();
  if ((g_tick.fetch_add(1, std::memory_order_relaxed) & 1023) == 0) Dump();
}
}  // namespace

void ngpu_83734370(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(0, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83734810(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(1, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83734A78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(2, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83734B10(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(3, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837351D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(4, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83735CF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(5, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736290(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(6, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837363D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(7, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736568(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(8, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736908(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(9, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837369A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(10, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736A28(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(11, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736DC8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(12, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736EC8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(13, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83736F48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(14, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737068(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(15, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837370F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(16, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737180(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(17, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837374E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(18, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837377C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(19, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737950(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(20, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737BB8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(21, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737C98(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(22, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737CB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(23, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737D08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(24, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737D48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(25, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737D58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(26, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83737DF0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(27, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83738A38(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(28, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837390C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(29, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83739188(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(30, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83739318(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(31, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83739360(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(32, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837397E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(33, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83739CF0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(34, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A088(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(35, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A3D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(36, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A4D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(37, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A5A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(38, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A7D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(39, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A8C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(40, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373A918(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(41, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B060(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(42, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B1F8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(43, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B2E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(44, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B3C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(45, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B4D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(46, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B790(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(47, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373B880(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(48, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373BAD8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(49, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373BBE0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(50, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373BC68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(51, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373BD50(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(52, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373C1F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(53, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373C720(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(54, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373CB08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(55, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373D570(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(56, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373E5B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(57, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373E848(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(58, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373E970(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(59, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373E9E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(60, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EA68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(61, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EA90(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(62, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EB20(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(63, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EBE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(64, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EC38(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(65, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EC48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(66, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373ECF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(67, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373ED40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(68, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373ED50(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(69, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EE40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(70, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373EF78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(71, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373F180(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(72, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373F498(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(73, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373F928(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(74, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373FA08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(75, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373FAF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(76, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8373FB10(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(77, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83740290(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(78, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83741B08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(79, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83741DC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(80, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83741ED8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(81, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83741F00(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(82, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83742128(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(83, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83742C10(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(84, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83743268(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(85, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83743F80(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(86, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83744D90(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(87, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837452C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(88, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837459D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(89, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83745B20(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(90, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83746F50(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(91, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83747498(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(92, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_837475C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(93, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83747790(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(94, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83747940(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(95, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83747BB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(96, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83748A18(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(97, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83748C08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(98, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83748F18(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(99, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83749AE0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(100, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83749BC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(101, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374B300(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(102, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374B6A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(103, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374BAC8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(104, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374C4D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(105, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374C5B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(106, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8374C728(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(107, r3, r4, r5, r6, r7, r8, r9, r10); }
