// GENERATED by tools/native_gpu/gen_gpu_cvars.py - do not edit by hand.
// The GPU cvars rexgpu-xenos.dll used to register, copied verbatim from the fork's plugin sources
// (D:/ng2_frameinterp/ng2-rexglue src/graphics, Vulkan excluded) so the exe owns them now the DLL is gone.
#include <cstdint>
#include <string>
#include <rex/cvar.h>

// from command_processor.cpp
REXCVAR_DEFINE_BOOL(gpu_log_unknown_registers, false, "GPU",
                    "Look every register write up and log unknown registers at debug level (costs a "
                    "lookup per write; off unless debugging)")
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

// from d3d12/command_processor.cpp
REXCVAR_DEFINE_BOOL(gpu_offload_to_native, false, "GPU/D3D12",
                    "Hand all GPU work to the in-app native renderer (the plugin only parses PM4 and feeds the bridge); needs the native backend enabled")
    .lifecycle(rex::cvar::Lifecycle::kRequiresRestart);

// from d3d12/command_processor.cpp
REXCVAR_DEFINE_BOOL(reveal_hold, true, "GPU/D3D12",
                    "After a load, show the stage only once it is complete (hides the partially drawn first frames)")
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

// from d3d12/command_processor.cpp
REXCVAR_DEFINE_INT32(reveal_hold_frames, 6, "GPU/D3D12",
                     "Consecutive complete frames that end the post-load reveal hold")
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

// from d3d12/command_processor.cpp
REXCVAR_DEFINE_INT32(reveal_hold_max_ms, 2500, "GPU/D3D12",
                     "The post-load reveal hold never lasts longer than this (ms)")
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

// from graphics_system.cpp
REXCVAR_DEFINE_BOOL(store_shaders, true, "GPU",
                    "Store shaders persistently and load them when loading games to avoid "
                    "runtime spikes and freezes when playing the game not for the first time.");

// from graphics_system.cpp
REXCVAR_DEFINE_STRING(swap_post_effect, "none", "GPU", "Swap post effect: none, fxaa, fxaa_extreme")
    .allowed({"none", "fxaa", "fxaa_extreme"})
    // Hot-reload since 2026-09-27: the app's settings screen changes it live and
    // the command processor takes a new value at any swap (a change callback
    // below pushes it); it used to be read once at init and marked
    // restart-required, so the screen's "applies immediately" was untrue.
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

// from command_processor.cpp
REXCVAR_DEFINE_INT32(wait_reg_mem_yield_ms, 2, "GPU",
                     "With vsync: poll a WAIT_REG_MEM packet with a yield for this many ms before sleeping "
                     "for its own interval (in-frame waits are short; a load screen's are not)")
    .lifecycle(rex::cvar::Lifecycle::kHotReload);

